### ISSUE TITLE
Cannot run OpenGL displays on lxplus

### ISSUE THREAD

**Issue by antonioiuliano2** [ShipSoft/FairShip#262]
Dear FairShip experts,

I am currently testing the new FairShip build on CVFMS proposed at today ship software meeting (https://indico.cern.ch/event/839565/).
The build and a test simulation work fine. However, launching the macro/eventDisplay.py script leads to

*** Break *** segmentation violation
without other messages

Othrer OGL drawings I have tested lead to the same result.

What could be the cause?

Best regards,
Antonio Iuliano

**Comment by siscia** [comment]
Very well!

Let me look into it! To be honest most of the test where focused on the python scripts.

You just run `python macro/eventDisplay.py` and it break with segmentation fault?

Thanks,
Simone

**Comment by siscia** [comment]
Also, what version?

2018 or 2020?

**Comment by antonioiuliano2** [comment]
Hi Simone,

I am using 2020 version, and I have launched macro/eventDisplay.py with the following syntax:

python -i $FAIRSHIP/macro/eventDisplay.py -f ship.conical.Genie-TGeant4.root -g geofile_full.conical.Genie-TGeant4.root

where the files ship.conical.Genie-TGeant4.root and geofile_full.conical.Genie-TGeant4.root.
I do not think this is however a problem with the python macro/eventDisplay.py script, since as I have said other simple OpenGL drawings reproduce the same issue.

I suggest a simple way to reproduce the issue is to try to run one of the ROOT ogl geometry tutorials:
root -l $ROOTSYS/tutorials/geom/geomAtlas.C
leads to the same segmentation violation (and naturally it should not do so)

**Comment by ThomasRuf** [comment]
it seems to be the same error which I get since December 2018 using the LHCb event display, which however does not use TEve:
#6  0x00007f6f57fbc5b6 in __memcpy_ssse3_back () from /lib64/libc.so.6
#7  0x00007f6f19271bdb in llvm::WritableMemoryBuffer::getNewUninitMemBuffer(unsigned long, llvm::Twine const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#8  0x00007f6f19271caf in getMemBufferCopyImpl(llvm::StringRef, llvm::Twine const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#9  0x00007f6f19271d30 in llvm::MemoryBuffer::getMemBufferCopy(llvm::StringRef, llvm::Twine const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#10 0x00007f6f1a2d92f5 in (anonymous namespace)::createELFDebugObject(llvm::object::ObjectFile const&, (anonymous namespace)::LoadedELFObjectInfo const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#11 0x00007f6f1a2d9db2 in (anonymous namespace)::LoadedELFObjectInfo::getObjectForDebug(llvm::object::ObjectFile const&) const () from /usr/lib64/libLLVM-6.0-rhel.so
#12 0x00007f6f1a288495 in (anonymous namespace)::GDBJITRegistrationListener::NotifyObjectEmitted(llvm::object::ObjectFile const&, llvm::RuntimeDyld::LoadedObjectInfo const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#13 0x00007f6f1a2a4f43 in llvm::MCJIT::NotifyObjectEmitted(llvm::object::ObjectFile const&, llvm::RuntimeDyld::LoadedObjectInfo const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#14 0x00007f6f1a2a7e07 in llvm::MCJIT::generateCodeForModule(llvm::Module*) () from /usr/lib64/libLLVM-6.0-rhel.so
#15 0x00007f6f1a2a4560 in llvm::MCJIT::finalizeObject() () from /usr/lib64/libLLVM-6.0-rhel.so
#16 0x00007f6f1a285f42 in LLVMGetPointerToGlobal () from /usr/lib64/libLLVM-6.0-rhel.so
#17 0x00007f6f1c5823f6 in llvmpipe_update_fs () from /usr/lib64/dri/swrast_dri.so
#18 0x00007f6f1c57a2d0 in llvmpipe_update_derived () from /usr/lib64/dri/swrast_dri.so
#19 0x00007f6f1c5657a6 in llvmpipe_draw_vbo () from /usr/lib64/dri/swrast_dri.so
#20 0x00007f6f1c1b2b93 in cso_draw_arrays () from /usr/lib64/dri/swrast_dri.so
#21 0x00007f6f1c00de61 in st_draw_quad () from /usr/lib64/dri/swrast_dri.so
#22 0x00007f6f1bff89b5 in st_Clear () from /usr/lib64/dri/swrast_dri.so
#23 0x00007f6f2a8f3817 in SoViewportRegion::GLRender(SoGLRenderAction*) () from /cvmfs/lhcb.cern.ch/lib/contrib/osc_vis/17.0.2/x86_64-centos7-gcc62-opt/lib/libourex_HEPVis.so
#24 0x00007f6f29f50838 in SoChildList::traverse(SoAction*, int, int) () from /cvmfs/lhcb.cern.ch/lib/contrib/osc_vis/17.0.2/x86_64-centos7-gcc62-opt/lib/libourex_CoinGL.so
#25 0x00007f6f29ee637f in SoBaseKit::doAction(SoAction*) () from /cvmfs/lhcb.cern.ch/lib/contrib/osc_vis/17.0.2/x86_64-centos7-gcc62-opt/lib/libourex_CoinGL.so

**Comment by siscia** [comment]
Does this happens also with the 2018 version?

**Comment by ThomasRuf** [comment]
i think it is an issue of slc6 versus slc7. For LHCb, I bypass the problem by running on slc6 machine.

**Comment by antonioiuliano2** [comment]
Yes,

I remember I was doing that too in the previous ./localBuild configuration.
However, now I cannot do that anymore because the slc6 folder version is missing in the sw CVFMS folder.

**Comment by siscia** [comment]
Hi all!

So to recap, I am able to reproduce the issue!

The window start but eventually it goes into Segmentation Fault.

```
[FairShip/latest] ~/private/ship2020 $> python -i $FAIRSHIP/macro/eventDisplay.py -f ship.conical.Pythia8-TGeant4.root -g geofile_full.conical.Pythia8-TGeant4.root 
FairShip setup for Pythia8
[INFO] Opening Geometry input file: geofile_full.conical.Pythia8-TGeant4.root
[INFO] The input consists out of the following trees and files: 
[INFO]  - cbmsim
[INFO]     - ship.conical.Pythia8-TGeant4.root
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
Info in <TGeoManager::SetTopVolume>: Top volume is cave. Master volume is cave
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Info in <TGeoManager::Voxelize>: Voxelizing...
Info in <TGeoManager::CountLevels>: max level = 9, max placements = 5058
Info in <TGeoManager::CloseGeometry>: 8486592 nodes/ 1081 volume UID's in FAIR geometry
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
[INFO] Parameter and input file are available, Assure that basic info is there for the run!

************************************************************* 
     initialisation for run id 1565007358
************************************************************* 
-I- FairRunTimeDB::InitContainer() FairBaseParSet
[ERROR] init() FairBaseParSet not initialized
Error in <FairRuntimeDb::initContainers()>: Error occured during initialization

************************************************************* 
     initialisation for run id 1565007358
************************************************************* 
-I- FairRunTimeDB::InitContainer() FairBaseParSet
[ERROR] init() FairBaseParSet not initialized
Error in <FairRuntimeDb::initContainers()>: Error occured during initialization
[INFO] Object ShipRpcPoint describing the branch in the folder structure was found
[INFO] Object strawtubesPoint describing the branch in the folder structure was found
[INFO] Object vetoPoint describing the branch in the folder structure was found
[INFO] Object TimeDetPoint describing the branch in the folder structure was found
[INFO] Object TargetPoint describing the branch in the folder structure was found
[INFO] Object EcalPoint describing the branch in the folder structure was found
[INFO] Object muonPoint describing the branch in the folder structure was found
TTree::Bronch:0: RuntimeWarning: FairEventHeader cannot be split, resetting splitlevel to 0
Info in <TGeoManager::SetVisLevel>: Automatic visible depth disabled

 *** Break *** segmentation violation
```
If you get something different, please let me know.

I must be honest that I am not an expert on this graphic things, but it may also not be related to graphics.

For what concern SLC6, it is phasing out, so my suggestion is to try to work on the SLC7 machine and figure out what caused this problems.

@antonioiuliano2 are you blocked by this, and you cannot do your work, or while I look into the problem you can still do your work? I guess you can still use the old installation mechanism.

**Comment by ThomasRuf** [comment]
Some more info. Setting up the root environment on lxplus with 
source /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.18.00/x86_64-centos7-gcc48-opt/bin/thisroot.sh

the examples in the root tutorial work:
root /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.18.00/src/tutorials/eve/geom_atlas.C

it is interesting to note that ROOT only offers gcc48 for centos7. For ubuntu gcc74 and for fedora gcc83.

could it be that when we make ROOT with slc7_x86-64/GCC-Toolchain/v6.2.0-alice1-1/, that we miss / or have wrong versions of graphics libraries?

Also, problem does not appear when using the local compiler version on Ubuntu.

**Comment by antonioiuliano2** [comment]
Hi Simone,

thank you for your concerning, but this luckily is not a work-blocking issue, since it only regards the display. I can do the heavy work on lxplus and then plot and save the displays from my local FairShip installations.

Best regards,
Antonio

**Comment by siscia** [comment]
I found this: https://forum.gsi.de/index.php?t=tree&goto=15553&#page_top

Does it help the slightness?

**Comment by ThomasRuf** [comment]
The OpenGL issue is a pure ROOT issue, it can be reproduced just with root, any script in tutorial /eve, fairroot is not involved. Thomas

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>




On Mon, Aug 12, 2019 at 4:48 PM +0200, "Simone Mosciatti" <notifications@github.com<mailto:notifications@github.com>> wrote:


I found this: https://forum.gsi.de/index.php?t=tree&goto=15553&#page_top

Does it help the slightness?

**Comment by siscia** [comment]
@ThomasRuf you are right! It seems quite weird though... And I didn't give much though to your direction.

It is our root version that causes issues.

We can reproduce with sourcing our environment first (both version), and the run the example.

```
source /cvmfs/ship.cern.ch/SHiP-2018/latest/setUp.sh
root /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.18.00/src/tutorials/eve/geom_atlas.C
```

**Comment by siscia** [comment]
I just pushed a fix on the `setUp.sh` script for both version of SHiP.

Does this solve the problem?

**Comment by ThomasRuf** [comment]
I tried on lxplus from my ubuntu VM:
source /cvmfs/ship.cern.ch/SHiP-2020/latest/setUp.sh 
alienv enter FairShip/latest
python -i $FAIRSHIP/macro/eventDisplay.py ...
 *** Break *** segmentation violation
...
#7  0x00007f41500cf866 in __memcpy_ssse3_back () from /lib64/libc.so.6
#8  0x00007f40fc6d6bdb in llvm::WritableMemoryBuffer::getNewUninitMemBuffer(unsigned long, llvm::Twine const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#9  0x00007f40fc6d6caf in getMemBufferCopyImpl(llvm::StringRef, llvm::Twine const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#10 0x00007f40fc6d6d30 in llvm::MemoryBuffer::getMemBufferCopy(llvm::StringRef, llvm::Twine const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#11 0x00007f40fd73e2f5 in (anonymous namespace)::createELFDebugObject(llvm::object::ObjectFile const&, (anonymous namespace)::LoadedELFObjectInfo const&) () from /usr/lib64/libLLVM-6.0-rhel.so
#12 0x00007f40fd73edb2 in (anonymous namespace)::LoadedELFObjectInfo::getObjectForDebug(llvm::object::ObjectFile const&) const () from /usr/lib64/libLLVM-6.0-rhel.so
#13 0x00007f40fd6ed495 in (anonymous namespace)::GDBJITRegistrationListener::NotifyObjectEmitted(llvm::object::ObjectFile const&, llvm::RuntimeDyld::LoadedObjectInfo const&) () from /usr/lib64/libLLVM-6.0-rhel.so
...

Did I missed something?

**Comment by antonioiuliano2** [comment]
I have tried also the /eve/geom_atlas.C tutorial and it unfortunately still does not work.

**Comment by ThomasRuf** [comment]
it seems that the new env variabl is not set:

source /cvmfs/ship.cern.ch/SHiP-2020/latest/setUp.sh 
[trufship@lxplus704 Shipbuild-2020]$ printenv LIBGL_DRIVERS_PATH
[trufship@lxplus704 Shipbuild-2020]$

**Comment by ThomasRuf** [comment]
with export LIBGL_DRIVERS_PATH=/cvmfs/sft.cern.ch/lcg/contrib/mesa/18.0.5/x86_64-centos7/lib64/dri 
the graphics works. Only issue, many messages of type:  TClassTable::Add:0: RuntimeWarning: class TEveGeoNodeEditor already in TClassTable

**Comment by ThomasRuf** [comment]
PS: and a problem with exit:

 *** Break *** segmentation violation
...
===========================================================
#7  0x0000000000000031 in ?? ()
#8  0x00007f43a7585006 in TEveTrackPropagator::~TEveTrackPropagator (this=0x7f43a7878e20 <TEveTrackPropagator::fgDefault>, __in_chrg=<optimized out>) at /root/ship-2020/sw/SOURCES/ROOT/v6-18-00_FAIRSHIP/v6-18-00/graf3d/eve/src/TEveTrackPropagator.cxx:270
#9  0x00007f43cbaf1c29 in __run_exit_handlers () from /lib64/libc.so.6
#10 0x00007f43cbaf1c77 in exit () from /lib64/libc.so.6
#11 0x00007f43cbada49c in __libc_start_main () from /lib64/libc.so.6
#12 0x000000000040066e in _start ()

**Comment by siscia** [comment]
Sorry... This needs more investigation.

It was working literally this morning when I asked you to check again.

**Comment by siscia** [comment]
Can you guys please re-try?

Also, if it does not work, please post the whole command that you used!

**Comment by antonioiuliano2** [comment]
Dear Simone,

thank you very much for your work and for your update, now both the eventDisplay and the ROOT tutorial work in lxplus without errors! Tested in lxplus7 with 2020 version.

Best regards,
Antonio Iuliano

**Comment by ThomasRuf** [comment]
I can confirm this.

**Comment by siscia** [comment]
I am running the ATLAS visualization which exists just fine.

Can this be related to the GenFit tracks that give similar problems when deleting?
Does the same problem appear with the default root version in lxplus?

**Comment by antonioiuliano2** [comment]
Dear all,
since the main issue has been solved and there are no other updates, I am closing this thread for now.
Eventually we can open a new one for the GenFit tracks issue.
Thank you for everyone for your help!
